name: Build and Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --noconfirm --onefile --windowed --name="TTML转LYS工具" --add-data="log;log" TTML_to_LYS_GUI.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: TTML转LYS工具
          path: dist/TTML转LYS工具.exe

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/TTML转LYS工具.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}